title: "WildVoltaireian"
description: "Say hello to my world."

url: "https://thevoltaireian.github.io/Website"
baseurl: ""

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - CONTRIBUTING.md
