title: "WildVoltaireian"
description: "Say hello to my world."
url: "https://wildvoltaireian.xyz"
baseurl: ""

markdown: kramdown
theme: null

permalink: /blog/:year/:month/:day/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - CONTRIBUTING.md